# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Brian D. Gerber"                                
  description: "Animal Ecology and Conservation Research" 
  image: img/leaf2.png
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Lab"
        href: lab/index.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "CV"
        href: cv/index.qmd

    # your social media handles
    right:
      - icon: google
        text: Scholar
        href: https://scholar.google.com/citations?user=ep25z9AAAAAJ&hl=en
      - icon: r-square-fill
        text: RG
        href: https://www.researchgate.net/profile/Brian-Gerber-4
      - icon: github
        text: Github
        href: https://github.com/bgerber123
      - icon: envelope
        text: Email
        href: "mailto:brian.gerber@colostate.edu"  
  
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Brian D. Gerber CC BY-SA 4.0</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      light: cosmo
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true